/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ga_ts;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        //Set our parameters
        int generationNumber = 1000;
        int popSize = 50;
        int poolSize = 10;
        double mutationRate = 0.10;

        //Generate our list of cities
        CityGenerator cityGen = new CityGenerator(150, -200,1400,30, true);
        cityGen.writeToCSVFile();
        ArrayList<City> cityList = cityGen.generatedCities;

        //Create our GA

        //Print the results
        System.out.println();
    }

}
